name: PermissionExecutor
version: 1.0
author: NickDoxa
main: net.oasisgames.pexec.Main
description: Join permissions system ran by LuckPerms and Floodgate created by Nick Doxa
depends: [LuckPerms]
api-version: 1.19